# 3.1 Dot Product of Vectors
**Problem**: How to compute the dot product of two vectors?
**Explanation**:
The dot product is the sum of element-wise multiplications:
$$a.b = \sum_{i=1}^{n}a_ib_i$$
It is used in ML for similarity checks and projections.

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [4]:
dot = np.dot(a, b)
print("Dot product:", dot)

Dot product: 32


# 3.2 Matrix Multiplication
**Problem**: How to multiply matrices?

**Explanation**:
Matrix multiplication combines rows and columns. In ML, this is how inputs get transformed by weights.

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [6]:
print("Matrix product:\n", A @ B)      # Using @ operator
print("Matrix product (np.dot):\n", np.dot(A, B))

Matrix product:
 [[19 22]
 [43 50]]
Matrix product (np.dot):
 [[19 22]
 [43 50]]


# 3.3 Transpose & Inverse
**Problem**: How to find the transpose and inverse of a matrix?

**Explanation**:

- **Transpose**: flips rows ↔ columns.
- **Inverse**: like dividing by a matrix.

(Only square, non-singular matrices have an inverse).

In [7]:
M = np.array([[1, 2], [3, 4]])

In [8]:
print("Transpose:\n", M.T)
print("Inverse:\n", np.linalg.inv(M))

Transpose:
 [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# 3.4 Determinant of a Matrix
**Problem**: How to compute a determinant?

**Explanation**:
The determinant tells us if a matrix is invertible and encodes information about scaling.

In [9]:
M = np.array([[1, 2], [3, 4]])

In [10]:
det = np.linalg.det(M)
print("Determinant:", det)

Determinant: -2.0000000000000004


# 3.5 Eigenvalues & Eigenvectors
**Problem**: How to compute eigenvalues and eigenvectors?

**Explanation**:
Eigenvalues & eigenvectors are fundamental in ML for PCA (dimensionality reduction).

$$Av = \lambda v$$

In [11]:
M = np.array([[4, -2], 
              [1,  1]])

In [12]:
eigvals, eigvecs = np.linalg.eig(M)

In [13]:
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


# 3.6 Solving Linear Equations

**Problem**: How to solve a system of equations $Ax = b$?

**Explanation**:
Instead of manually inverting matrices, NumPy provides `np.linalg.solve`.
Example system:
$$2x + y = 5$$
$$x-y = 1$$

In [14]:
A = np.array([[2, 1], [1, -1]])
b = np.array([5, 1])

In [15]:
solution = np.linalg.solve(A, b)
print("Solution:", solution)

Solution: [2. 1.]


# 3.7 Rank of a Matrix
**Problem**: How to check the rank of a matrix?

**Explanation**:
Rank tells us the number of linearly independent rows/columns. In ML, it determines feature redundancy.


In [16]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [17]:
rank = np.linalg.matrix_rank(M)
print("Rank:", rank)

Rank: 2


# 3.8 Orthogonality Check
**Problem**: How to check if two vectors are orthogonal?

**Explanation**:
Two vectors are orthogonal if their dot product = 0.

In [18]:
u = np.array([1, 0])
v = np.array([0, 1])

In [19]:
print("Dot product:", np.dot(u, v))

Dot product: 0
