# 1.1 Creating Arrays
**Problem**: How do we create NumPy arrays from lists or directly using NumPy functions?

**Explanation**: A NumPy array is like a super-powered Python list that supports vectorized operations (fast calculations without loops). You can create arrays from Python lists or with NumPy functions like `np.zeros`, `np.arange`, etc.

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print("Array from list: ", arr1)

Array from list:  [1 2 3 4 5]


In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
zeros = np.zeros((2, 3))
print("Zeros:\n", zeros)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
ones = np.ones((3, 3))
print("Ones:\n", ones)

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
identity = np.eye(3)
print("Indentity Matrix:\n", identity)

Indentity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
rand = np.random.rand(2, 2)
print("Random Array:\n", rand)

Random Array:
 [[0.74247144 0.71092681]
 [0.9136465  0.87395103]]


# 1.2 Array Attributes
**Problem**: How do we check array properties (shape, size, datatype)?

**Explanation**: In ML tasks, knowing the shape of arrays is critical (e.g., features vs samples). NumPy gives us quick ways to inspect arrays.

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape: ", arr.shape) # (rows, columns)
print("Size: ", arr.size) #(total elements)
print("Data Type: ", arr.dtype)
print("Number of elements: ", arr.ndim) # Dimentions

Shape:  (2, 3)
Size:  6
Data Type:  int64
Number of elements:  2


# 1.3 Reshape, Flatten, Transpose
**Problem**: How do we change array shapes?

**Explanation**: Data often comes in different formats (rows, columns, images). Reshaping is essential

- `reshape`: change dimensions
- `flatten`: convert to 1D
- `transpose`: swap rows & columns 

In [10]:
arr = np.arange(12)
print("Original: ", arr)

Original:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
reshaped = arr.reshape(3, 4)
print("Reshaped (3x4):\n", reshaped)

Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
flattened = reshaped.flatten()
print("Flattened: ", flattened)

Flattened:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
transposed = reshaped.T
print(transposed)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# 1.1 Indexing & Slicing
**Problem**: How do we access elements in arrays?

**Explanation**: 

- **Indexing**: Use row & column positions.
- **Slicing**: Extract sub-arrays with `[start:end:step]`.
- **Fancy Indexing**: Select multiple positions at once.
- **Boolean Indexing**: Filter based on conditions.

In [14]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Element at (1,2): ", arr[1, 2])

Element at (1,2):  60


In [15]:
print("First two rows:\n", arr[:2])

First two rows:
 [[10 20 30]
 [40 50 60]]


In [20]:
print("Last column: ", arr[:, -1])

Last column:  [30 60 90]


In [21]:
print("Elements at (0, 0), (1, 1), (2, 2): ", arr[[0, 1, 2], [0, 1, 2]])

Elements at (0, 0), (1, 1), (2, 2):  [10 50 90]


In [22]:
print("Values > 50: ", arr[arr > 50])

Values > 50:  [60 70 80 90]


# 1.1 Generate Arrays with `arange` and `linspace`
**Problem**: How do we create sequences of numbers?

**Explanation**:

- `arange[start, stop, step]`: like Python range but returns an array.
- `linspace(start, stop, num)`: evenly spaced numbers.

In [23]:
print("arange(0, 10, 2): ", np.arange(0, 10, 2))

arange(0, 10, 2):  [0 2 4 6 8]


In [24]:
print("linspace(0, 1, 5): ", np.linspace(0, 1, 5))

linspace(0, 1, 5):  [0.   0.25 0.5  0.75 1.  ]
